/*
 * generated by Xtext
 */
package co.edu.uniandes.miso4202.ehicletax.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import co.edu.uniandes.miso4202.ehicletax.ui.internal.VtdslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VtdslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VtdslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VtdslActivator.getInstance().getInjector(VtdslActivator.CO_EDU_UNIANDES_MISO4202_EHICLETAX_VTDSL);
	}
	
}
