/*
 * generated by Xtext
 */
package co.edu.uniandes.miso4202.ehicletax.ui.contentassist

import co.edu.uniandes.miso4202.ehicletax.ui.contentassist.AbstractVtdslProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class VtdslProposalProvider extends AbstractVtdslProposalProvider {
}
