/*
 * generated by Xtext
 */
package co.edu.uniandes.miso4202.ehicletax.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VtdslUiModule extends co.edu.uniandes.miso4202.ehicletax.ui.AbstractVtdslUiModule {
	public VtdslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
