/*
 * generated by Xtext
 */
package co.edu.uniandes.miso4202.ehicletax;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VtdslRuntimeModule extends co.edu.uniandes.miso4202.ehicletax.AbstractVtdslRuntimeModule {

}
