/**
 * generated by Xtext
 */
package co.edu.uniandes.miso4202.ehicletax.validation;

import co.edu.uniandes.miso4202.ehicletax.validation.AbstractVtdslValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class VtdslValidator extends AbstractVtdslValidator {
}
