/*
* generated by Xtext
*/
package co.edu.uniandes.miso4202.ehicletax.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VtdslAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("co/edu/uniandes/miso4202/ehicletax/parser/antlr/internal/InternalVtdsl.tokens");
	}
}
